services:
  app-debug:
    image: kienghok/scholarship_portals:debug
    container_name: scholarship_portal_debug
    ports:
      - "8080:8080"  # map container port 8080 to host port 8081
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      EMAIL_VERIFICATION_API_URL: ${EMAIL_VERIFICATION_API_URL}
      EMAIL_API_KEY: ${EMAIL_API_KEY}
      REMINDER_EMAIL_API_KEY: ${REMINDER_EMAIL_API_KEY}
      REMINDER_EMAIL_API_URL: ${REMINDER_EMAIL_API_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      GIN_MODE: debug 