// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateScholarship.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createScholarship = `-- name: CreateScholarship :one
INSERT INTO scholarships (
    title,
    provider,
    description,
    institution_info,
    requirements,
    extra_notes,
    deadline_end,
    official_link,
    categories,
    photo_url
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, provider
`

type CreateScholarshipParams struct {
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	Categories      pqtype.NullRawMessage `json:"categories"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
}

type CreateScholarshipRow struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Provider string `json:"provider"`
}

func (q *Queries) CreateScholarship(ctx context.Context, arg CreateScholarshipParams) (CreateScholarshipRow, error) {
	row := q.queryRow(ctx, q.createScholarshipStmt, createScholarship,
		arg.Title,
		arg.Provider,
		arg.Description,
		arg.InstitutionInfo,
		arg.Requirements,
		arg.ExtraNotes,
		arg.DeadlineEnd,
		arg.OfficialLink,
		arg.Categories,
		arg.PhotoUrl,
	)
	var i CreateScholarshipRow
	err := row.Scan(&i.ID, &i.Title, &i.Provider)
	return i, err
}

const createScholarshipWithDetails = `-- name: CreateScholarshipWithDetails :one
INSERT INTO scholarships (
    title,
    provider,
    description,
    institution_info,
    requirements,
    extra_notes,
    deadline_end,
    official_link,
    categories
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, categories, created_at, updated_at, institution_code
`

type CreateScholarshipWithDetailsParams struct {
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	Categories      pqtype.NullRawMessage `json:"categories"`
}

func (q *Queries) CreateScholarshipWithDetails(ctx context.Context, arg CreateScholarshipWithDetailsParams) (Scholarship, error) {
	row := q.queryRow(ctx, q.createScholarshipWithDetailsStmt, createScholarshipWithDetails,
		arg.Title,
		arg.Provider,
		arg.Description,
		arg.InstitutionInfo,
		arg.Requirements,
		arg.ExtraNotes,
		arg.DeadlineEnd,
		arg.OfficialLink,
		arg.Categories,
	)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Provider,
		&i.Description,
		&i.InstitutionInfo,
		&i.Requirements,
		&i.ExtraNotes,
		&i.DeadlineEnd,
		&i.OfficialLink,
		&i.PhotoUrl,
		&i.Categories,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstitutionCode,
	)
	return i, err
}

const deleteScholarshipByID = `-- name: DeleteScholarshipByID :exec
DELETE FROM scholarships
WHERE id = $1
`

func (q *Queries) DeleteScholarshipByID(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteScholarshipByIDStmt, deleteScholarshipByID, id)
	return err
}
