// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateUser.sql

package db

import (
	"context"
	"database/sql"
)

const createStudentProfile = `-- name: CreateStudentProfile :exec
INSERT INTO student_profiles (student_id)
VALUES ($1)
`

func (q *Queries) CreateStudentProfile(ctx context.Context, studentID int32) error {
	_, err := q.exec(ctx, q.createStudentProfileStmt, createStudentProfile, studentID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    fullname, 
    email, 
    password_hash, 
    phone_number, 
    high_school, 
    grade_level, 
    diploma_year
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, fullname, email, created_at, updated_at
`

type CreateUserParams struct {
	Fullname     sql.NullString `json:"fullname"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	HighSchool   sql.NullString `json:"high_school"`
	GradeLevel   sql.NullInt32  `json:"grade_level"`
	DiplomaYear  sql.NullInt32  `json:"diploma_year"`
}

type CreateUserRow struct {
	ID        int32          `json:"id"`
	Fullname  sql.NullString `json:"fullname"`
	Email     string         `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Fullname,
		arg.Email,
		arg.PasswordHash,
		arg.PhoneNumber,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
