// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateUser.sql

package db

import (
	"context"
	"database/sql"
)

const checkUserExistByEmail = `-- name: CheckUserExistByEmail :one
SELECT email, email_verified 
FROM users 
WHERE email = $1
`

type CheckUserExistByEmailRow struct {
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"email_verified"`
}

func (q *Queries) CheckUserExistByEmail(ctx context.Context, email string) (CheckUserExistByEmailRow, error) {
	row := q.queryRow(ctx, q.checkUserExistByEmailStmt, checkUserExistByEmail, email)
	var i CheckUserExistByEmailRow
	err := row.Scan(&i.Email, &i.EmailVerified)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    fullname, 
    email,
    password_hash,
    email_verified
) VALUES ($1, $2, $3, $4)
RETURNING id, fullname, email, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	PasswordHash  sql.NullString `json:"password_hash"`
	EmailVerified sql.NullBool   `json:"email_verified"`
}

type CreateUserRow struct {
	ID            int32          `json:"id"`
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Fullname,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, fullname, email, password_hash, email_verified, created_at, updated_at
FROM users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            int32          `json:"id"`
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	PasswordHash  sql.NullString `json:"password_hash"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, fullname, email, password_hash, email_verified, created_at, updated_at
FROM users 
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            int32          `json:"id"`
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	PasswordHash  sql.NullString `json:"password_hash"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDOrEmail = `-- name: GetUserByIDOrEmail :one
SELECT 
    id,
    fullname,
    email,
    password_hash,
    email_verified,
    created_at,
    updated_at
FROM users
WHERE ($1::int IS NOT NULL AND id = $1) OR ($2::text IS NOT NULL AND email = $2)
`

type GetUserByIDOrEmailParams struct {
	Column1 int32  `json:"column_1"`
	Column2 string `json:"column_2"`
}

type GetUserByIDOrEmailRow struct {
	ID            int32          `json:"id"`
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	PasswordHash  sql.NullString `json:"password_hash"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByIDOrEmail(ctx context.Context, arg GetUserByIDOrEmailParams) (GetUserByIDOrEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByIDOrEmailStmt, getUserByIDOrEmail, arg.Column1, arg.Column2)
	var i GetUserByIDOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET email_verified = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.verifyUserEmailStmt, verifyUserEmail, id)
	return err
}
