// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateAdmin.sql

package db

import (
	"context"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, fullname, email, password_hash, totp_secret, is_two_factor, created_at, updated_at
FROM admins 
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.queryRow(ctx, q.getAdminByEmailStmt, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsTwoFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, fullname, email, password_hash, totp_secret, is_two_factor, created_at, updated_at
FROM admins 
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int32) (Admin, error) {
	row := q.queryRow(ctx, q.getAdminByIDStmt, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsTwoFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByIDOrEmail = `-- name: GetAdminByIDOrEmail :one
SELECT 
    id,
    fullname,
    email,
    password_hash,
    totp_secret,
    is_two_factor,
    created_at,
    updated_at
FROM admins
WHERE ($1::bigint IS NOT NULL AND id = $1) OR ($2::text IS NOT NULL AND email = $2)
`

type GetAdminByIDOrEmailParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) GetAdminByIDOrEmail(ctx context.Context, arg GetAdminByIDOrEmailParams) (Admin, error) {
	row := q.queryRow(ctx, q.getAdminByIDOrEmailStmt, getAdminByIDOrEmail, arg.Column1, arg.Column2)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.IsTwoFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
