// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addFavoriteStmt, err = db.PrepareContext(ctx, addFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query AddFavorite: %w", err)
	}
	if q.adminUpdateUserTOTPSecretStmt, err = db.PrepareContext(ctx, adminUpdateUserTOTPSecret); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdateUserTOTPSecret: %w", err)
	}
	if q.createScholarshipStmt, err = db.PrepareContext(ctx, createScholarship); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScholarship: %w", err)
	}
	if q.createScholarshipWithDetailsStmt, err = db.PrepareContext(ctx, createScholarshipWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScholarshipWithDetails: %w", err)
	}
	if q.createStudentProfileStmt, err = db.PrepareContext(ctx, createStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStudentProfile: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteScholarshipByIDStmt, err = db.PrepareContext(ctx, deleteScholarshipByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScholarshipByID: %w", err)
	}
	if q.enableAdmin2FAStmt, err = db.PrepareContext(ctx, enableAdmin2FA); err != nil {
		return nil, fmt.Errorf("error preparing query EnableAdmin2FA: %w", err)
	}
	if q.getAdminByIDOrEmailStmt, err = db.PrepareContext(ctx, getAdminByIDOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminByIDOrEmail: %w", err)
	}
	if q.getAllScholarshipsStmt, err = db.PrepareContext(ctx, getAllScholarships); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllScholarships: %w", err)
	}
	if q.getScholarshipByIDStmt, err = db.PrepareContext(ctx, getScholarshipByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipByID: %w", err)
	}
	if q.getScholarshipsByIDsStmt, err = db.PrepareContext(ctx, getScholarshipsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipsByIDs: %w", err)
	}
	if q.getScholarshipsByInstitutionCodeLikeStmt, err = db.PrepareContext(ctx, getScholarshipsByInstitutionCodeLike); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipsByInstitutionCodeLike: %w", err)
	}
	if q.getUserByIDOrEmailStmt, err = db.PrepareContext(ctx, getUserByIDOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByIDOrEmail: %w", err)
	}
	if q.getUserWithProfileStmt, err = db.PrepareContext(ctx, getUserWithProfile); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithProfile: %w", err)
	}
	if q.listFavoritesByUserStmt, err = db.PrepareContext(ctx, listFavoritesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListFavoritesByUser: %w", err)
	}
	if q.removeFavoriteStmt, err = db.PrepareContext(ctx, removeFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveFavorite: %w", err)
	}
	if q.searchScholarshipsStmt, err = db.PrepareContext(ctx, searchScholarships); err != nil {
		return nil, fmt.Errorf("error preparing query SearchScholarships: %w", err)
	}
	if q.updateStudentProfileStmt, err = db.PrepareContext(ctx, updateStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStudentProfile: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	if q.upsertOauthLoginStmt, err = db.PrepareContext(ctx, upsertOauthLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOauthLogin: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addFavoriteStmt != nil {
		if cerr := q.addFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addFavoriteStmt: %w", cerr)
		}
	}
	if q.adminUpdateUserTOTPSecretStmt != nil {
		if cerr := q.adminUpdateUserTOTPSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdateUserTOTPSecretStmt: %w", cerr)
		}
	}
	if q.createScholarshipStmt != nil {
		if cerr := q.createScholarshipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScholarshipStmt: %w", cerr)
		}
	}
	if q.createScholarshipWithDetailsStmt != nil {
		if cerr := q.createScholarshipWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScholarshipWithDetailsStmt: %w", cerr)
		}
	}
	if q.createStudentProfileStmt != nil {
		if cerr := q.createStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStudentProfileStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteScholarshipByIDStmt != nil {
		if cerr := q.deleteScholarshipByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScholarshipByIDStmt: %w", cerr)
		}
	}
	if q.enableAdmin2FAStmt != nil {
		if cerr := q.enableAdmin2FAStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enableAdmin2FAStmt: %w", cerr)
		}
	}
	if q.getAdminByIDOrEmailStmt != nil {
		if cerr := q.getAdminByIDOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminByIDOrEmailStmt: %w", cerr)
		}
	}
	if q.getAllScholarshipsStmt != nil {
		if cerr := q.getAllScholarshipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllScholarshipsStmt: %w", cerr)
		}
	}
	if q.getScholarshipByIDStmt != nil {
		if cerr := q.getScholarshipByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipByIDStmt: %w", cerr)
		}
	}
	if q.getScholarshipsByIDsStmt != nil {
		if cerr := q.getScholarshipsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipsByIDsStmt: %w", cerr)
		}
	}
	if q.getScholarshipsByInstitutionCodeLikeStmt != nil {
		if cerr := q.getScholarshipsByInstitutionCodeLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipsByInstitutionCodeLikeStmt: %w", cerr)
		}
	}
	if q.getUserByIDOrEmailStmt != nil {
		if cerr := q.getUserByIDOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDOrEmailStmt: %w", cerr)
		}
	}
	if q.getUserWithProfileStmt != nil {
		if cerr := q.getUserWithProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithProfileStmt: %w", cerr)
		}
	}
	if q.listFavoritesByUserStmt != nil {
		if cerr := q.listFavoritesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFavoritesByUserStmt: %w", cerr)
		}
	}
	if q.removeFavoriteStmt != nil {
		if cerr := q.removeFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeFavoriteStmt: %w", cerr)
		}
	}
	if q.searchScholarshipsStmt != nil {
		if cerr := q.searchScholarshipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchScholarshipsStmt: %w", cerr)
		}
	}
	if q.updateStudentProfileStmt != nil {
		if cerr := q.updateStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStudentProfileStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	if q.upsertOauthLoginStmt != nil {
		if cerr := q.upsertOauthLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOauthLoginStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                       DBTX
	tx                                       *sql.Tx
	addFavoriteStmt                          *sql.Stmt
	adminUpdateUserTOTPSecretStmt            *sql.Stmt
	createScholarshipStmt                    *sql.Stmt
	createScholarshipWithDetailsStmt         *sql.Stmt
	createStudentProfileStmt                 *sql.Stmt
	createUserStmt                           *sql.Stmt
	deleteScholarshipByIDStmt                *sql.Stmt
	enableAdmin2FAStmt                       *sql.Stmt
	getAdminByIDOrEmailStmt                  *sql.Stmt
	getAllScholarshipsStmt                   *sql.Stmt
	getScholarshipByIDStmt                   *sql.Stmt
	getScholarshipsByIDsStmt                 *sql.Stmt
	getScholarshipsByInstitutionCodeLikeStmt *sql.Stmt
	getUserByIDOrEmailStmt                   *sql.Stmt
	getUserWithProfileStmt                   *sql.Stmt
	listFavoritesByUserStmt                  *sql.Stmt
	removeFavoriteStmt                       *sql.Stmt
	searchScholarshipsStmt                   *sql.Stmt
	updateStudentProfileStmt                 *sql.Stmt
	updateUserProfileStmt                    *sql.Stmt
	upsertOauthLoginStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                       tx,
		tx:                                       tx,
		addFavoriteStmt:                          q.addFavoriteStmt,
		adminUpdateUserTOTPSecretStmt:            q.adminUpdateUserTOTPSecretStmt,
		createScholarshipStmt:                    q.createScholarshipStmt,
		createScholarshipWithDetailsStmt:         q.createScholarshipWithDetailsStmt,
		createStudentProfileStmt:                 q.createStudentProfileStmt,
		createUserStmt:                           q.createUserStmt,
		deleteScholarshipByIDStmt:                q.deleteScholarshipByIDStmt,
		enableAdmin2FAStmt:                       q.enableAdmin2FAStmt,
		getAdminByIDOrEmailStmt:                  q.getAdminByIDOrEmailStmt,
		getAllScholarshipsStmt:                   q.getAllScholarshipsStmt,
		getScholarshipByIDStmt:                   q.getScholarshipByIDStmt,
		getScholarshipsByIDsStmt:                 q.getScholarshipsByIDsStmt,
		getScholarshipsByInstitutionCodeLikeStmt: q.getScholarshipsByInstitutionCodeLikeStmt,
		getUserByIDOrEmailStmt:                   q.getUserByIDOrEmailStmt,
		getUserWithProfileStmt:                   q.getUserWithProfileStmt,
		listFavoritesByUserStmt:                  q.listFavoritesByUserStmt,
		removeFavoriteStmt:                       q.removeFavoriteStmt,
		searchScholarshipsStmt:                   q.searchScholarshipsStmt,
		updateStudentProfileStmt:                 q.updateStudentProfileStmt,
		updateUserProfileStmt:                    q.updateUserProfileStmt,
		upsertOauthLoginStmt:                     q.upsertOauthLoginStmt,
	}
}
