// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addFavoriteStmt, err = db.PrepareContext(ctx, addFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query AddFavorite: %w", err)
	}
	if q.adminUpdateUserTOTPSecretStmt, err = db.PrepareContext(ctx, adminUpdateUserTOTPSecret); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdateUserTOTPSecret: %w", err)
	}
	if q.checkUserExistByEmailStmt, err = db.PrepareContext(ctx, checkUserExistByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query CheckUserExistByEmail: %w", err)
	}
	if q.cleanupExpiredVerificationsStmt, err = db.PrepareContext(ctx, cleanupExpiredVerifications); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupExpiredVerifications: %w", err)
	}
	if q.createEmailVerificationStmt, err = db.PrepareContext(ctx, createEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEmailVerification: %w", err)
	}
	if q.createOAuthLoginStmt, err = db.PrepareContext(ctx, createOAuthLogin); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOAuthLogin: %w", err)
	}
	if q.createScholarshipStmt, err = db.PrepareContext(ctx, createScholarship); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScholarship: %w", err)
	}
	if q.createScholarshipWithDetailsStmt, err = db.PrepareContext(ctx, createScholarshipWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScholarshipWithDetails: %w", err)
	}
	if q.createStudentProfileStmt, err = db.PrepareContext(ctx, createStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStudentProfile: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteEmailVerificationsByUserIDStmt, err = db.PrepareContext(ctx, deleteEmailVerificationsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmailVerificationsByUserID: %w", err)
	}
	if q.deleteExpiredVerificationsStmt, err = db.PrepareContext(ctx, deleteExpiredVerifications); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredVerifications: %w", err)
	}
	if q.deleteOAuthLoginStmt, err = db.PrepareContext(ctx, deleteOAuthLogin); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOAuthLogin: %w", err)
	}
	if q.deleteScholarshipByIDStmt, err = db.PrepareContext(ctx, deleteScholarshipByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScholarshipByID: %w", err)
	}
	if q.deleteStudentProfileStmt, err = db.PrepareContext(ctx, deleteStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteStudentProfile: %w", err)
	}
	if q.enableAdmin2FAStmt, err = db.PrepareContext(ctx, enableAdmin2FA); err != nil {
		return nil, fmt.Errorf("error preparing query EnableAdmin2FA: %w", err)
	}
	if q.getActiveScholarshipsStmt, err = db.PrepareContext(ctx, getActiveScholarships); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveScholarships: %w", err)
	}
	if q.getAdminByEmailStmt, err = db.PrepareContext(ctx, getAdminByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminByEmail: %w", err)
	}
	if q.getAdminByIDStmt, err = db.PrepareContext(ctx, getAdminByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminByID: %w", err)
	}
	if q.getAdminByIDOrEmailStmt, err = db.PrepareContext(ctx, getAdminByIDOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminByIDOrEmail: %w", err)
	}
	if q.getAllScholarshipsStmt, err = db.PrepareContext(ctx, getAllScholarships); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllScholarships: %w", err)
	}
	if q.getEmailVerificationByTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByToken: %w", err)
	}
	if q.getEmailVerificationByUserIDStmt, err = db.PrepareContext(ctx, getEmailVerificationByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByUserID: %w", err)
	}
	if q.getLatestVerificationByEmailStmt, err = db.PrepareContext(ctx, getLatestVerificationByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestVerificationByEmail: %w", err)
	}
	if q.getOAuthLoginByProviderStmt, err = db.PrepareContext(ctx, getOAuthLoginByProvider); err != nil {
		return nil, fmt.Errorf("error preparing query GetOAuthLoginByProvider: %w", err)
	}
	if q.getOAuthLoginsByUserIDStmt, err = db.PrepareContext(ctx, getOAuthLoginsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOAuthLoginsByUserID: %w", err)
	}
	if q.getRemindersForTodayStmt, err = db.PrepareContext(ctx, getRemindersForToday); err != nil {
		return nil, fmt.Errorf("error preparing query GetRemindersForToday: %w", err)
	}
	if q.getScholarshipByIDStmt, err = db.PrepareContext(ctx, getScholarshipByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipByID: %w", err)
	}
	if q.getScholarshipsByIDsStmt, err = db.PrepareContext(ctx, getScholarshipsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipsByIDs: %w", err)
	}
	if q.getScholarshipsByInstitutionCodeLikeStmt, err = db.PrepareContext(ctx, getScholarshipsByInstitutionCodeLike); err != nil {
		return nil, fmt.Errorf("error preparing query GetScholarshipsByInstitutionCodeLike: %w", err)
	}
	if q.getStudentProfileStmt, err = db.PrepareContext(ctx, getStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudentProfile: %w", err)
	}
	if q.getUnverifiedUserByEmailStmt, err = db.PrepareContext(ctx, getUnverifiedUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUnverifiedUserByEmail: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByIDOrEmailStmt, err = db.PrepareContext(ctx, getUserByIDOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByIDOrEmail: %w", err)
	}
	if q.getUserByOAuthProviderStmt, err = db.PrepareContext(ctx, getUserByOAuthProvider); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByOAuthProvider: %w", err)
	}
	if q.getUserWithStudentProfileStmt, err = db.PrepareContext(ctx, getUserWithStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithStudentProfile: %w", err)
	}
	if q.listFavoritesByUserStmt, err = db.PrepareContext(ctx, listFavoritesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListFavoritesByUser: %w", err)
	}
	if q.markEmailVerificationAsUsedStmt, err = db.PrepareContext(ctx, markEmailVerificationAsUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEmailVerificationAsUsed: %w", err)
	}
	if q.removeFavoriteStmt, err = db.PrepareContext(ctx, removeFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveFavorite: %w", err)
	}
	if q.searchScholarshipsStmt, err = db.PrepareContext(ctx, searchScholarships); err != nil {
		return nil, fmt.Errorf("error preparing query SearchScholarships: %w", err)
	}
	if q.searchScholarshipsByProgramsStmt, err = db.PrepareContext(ctx, searchScholarshipsByPrograms); err != nil {
		return nil, fmt.Errorf("error preparing query SearchScholarshipsByPrograms: %w", err)
	}
	if q.updateFavoriteStatusStmt, err = db.PrepareContext(ctx, updateFavoriteStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFavoriteStatus: %w", err)
	}
	if q.updateOAuthLoginStmt, err = db.PrepareContext(ctx, updateOAuthLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOAuthLogin: %w", err)
	}
	if q.updateScholarshipStmt, err = db.PrepareContext(ctx, updateScholarship); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateScholarship: %w", err)
	}
	if q.updateScholarshipJSONBStmt, err = db.PrepareContext(ctx, updateScholarshipJSONB); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateScholarshipJSONB: %w", err)
	}
	if q.updateStudentProfileStmt, err = db.PrepareContext(ctx, updateStudentProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStudentProfile: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	if q.upsertOauthLoginStmt, err = db.PrepareContext(ctx, upsertOauthLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOauthLogin: %w", err)
	}
	if q.verifyUserEmailStmt, err = db.PrepareContext(ctx, verifyUserEmail); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyUserEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addFavoriteStmt != nil {
		if cerr := q.addFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addFavoriteStmt: %w", cerr)
		}
	}
	if q.adminUpdateUserTOTPSecretStmt != nil {
		if cerr := q.adminUpdateUserTOTPSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdateUserTOTPSecretStmt: %w", cerr)
		}
	}
	if q.checkUserExistByEmailStmt != nil {
		if cerr := q.checkUserExistByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkUserExistByEmailStmt: %w", cerr)
		}
	}
	if q.cleanupExpiredVerificationsStmt != nil {
		if cerr := q.cleanupExpiredVerificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupExpiredVerificationsStmt: %w", cerr)
		}
	}
	if q.createEmailVerificationStmt != nil {
		if cerr := q.createEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEmailVerificationStmt: %w", cerr)
		}
	}
	if q.createOAuthLoginStmt != nil {
		if cerr := q.createOAuthLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOAuthLoginStmt: %w", cerr)
		}
	}
	if q.createScholarshipStmt != nil {
		if cerr := q.createScholarshipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScholarshipStmt: %w", cerr)
		}
	}
	if q.createScholarshipWithDetailsStmt != nil {
		if cerr := q.createScholarshipWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScholarshipWithDetailsStmt: %w", cerr)
		}
	}
	if q.createStudentProfileStmt != nil {
		if cerr := q.createStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStudentProfileStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteEmailVerificationsByUserIDStmt != nil {
		if cerr := q.deleteEmailVerificationsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmailVerificationsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteExpiredVerificationsStmt != nil {
		if cerr := q.deleteExpiredVerificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredVerificationsStmt: %w", cerr)
		}
	}
	if q.deleteOAuthLoginStmt != nil {
		if cerr := q.deleteOAuthLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOAuthLoginStmt: %w", cerr)
		}
	}
	if q.deleteScholarshipByIDStmt != nil {
		if cerr := q.deleteScholarshipByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScholarshipByIDStmt: %w", cerr)
		}
	}
	if q.deleteStudentProfileStmt != nil {
		if cerr := q.deleteStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStudentProfileStmt: %w", cerr)
		}
	}
	if q.enableAdmin2FAStmt != nil {
		if cerr := q.enableAdmin2FAStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enableAdmin2FAStmt: %w", cerr)
		}
	}
	if q.getActiveScholarshipsStmt != nil {
		if cerr := q.getActiveScholarshipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveScholarshipsStmt: %w", cerr)
		}
	}
	if q.getAdminByEmailStmt != nil {
		if cerr := q.getAdminByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminByEmailStmt: %w", cerr)
		}
	}
	if q.getAdminByIDStmt != nil {
		if cerr := q.getAdminByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminByIDStmt: %w", cerr)
		}
	}
	if q.getAdminByIDOrEmailStmt != nil {
		if cerr := q.getAdminByIDOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminByIDOrEmailStmt: %w", cerr)
		}
	}
	if q.getAllScholarshipsStmt != nil {
		if cerr := q.getAllScholarshipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllScholarshipsStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByTokenStmt != nil {
		if cerr := q.getEmailVerificationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByTokenStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByUserIDStmt != nil {
		if cerr := q.getEmailVerificationByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByUserIDStmt: %w", cerr)
		}
	}
	if q.getLatestVerificationByEmailStmt != nil {
		if cerr := q.getLatestVerificationByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestVerificationByEmailStmt: %w", cerr)
		}
	}
	if q.getOAuthLoginByProviderStmt != nil {
		if cerr := q.getOAuthLoginByProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOAuthLoginByProviderStmt: %w", cerr)
		}
	}
	if q.getOAuthLoginsByUserIDStmt != nil {
		if cerr := q.getOAuthLoginsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOAuthLoginsByUserIDStmt: %w", cerr)
		}
	}
	if q.getRemindersForTodayStmt != nil {
		if cerr := q.getRemindersForTodayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRemindersForTodayStmt: %w", cerr)
		}
	}
	if q.getScholarshipByIDStmt != nil {
		if cerr := q.getScholarshipByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipByIDStmt: %w", cerr)
		}
	}
	if q.getScholarshipsByIDsStmt != nil {
		if cerr := q.getScholarshipsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipsByIDsStmt: %w", cerr)
		}
	}
	if q.getScholarshipsByInstitutionCodeLikeStmt != nil {
		if cerr := q.getScholarshipsByInstitutionCodeLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScholarshipsByInstitutionCodeLikeStmt: %w", cerr)
		}
	}
	if q.getStudentProfileStmt != nil {
		if cerr := q.getStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudentProfileStmt: %w", cerr)
		}
	}
	if q.getUnverifiedUserByEmailStmt != nil {
		if cerr := q.getUnverifiedUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUnverifiedUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByIDOrEmailStmt != nil {
		if cerr := q.getUserByIDOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDOrEmailStmt: %w", cerr)
		}
	}
	if q.getUserByOAuthProviderStmt != nil {
		if cerr := q.getUserByOAuthProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByOAuthProviderStmt: %w", cerr)
		}
	}
	if q.getUserWithStudentProfileStmt != nil {
		if cerr := q.getUserWithStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithStudentProfileStmt: %w", cerr)
		}
	}
	if q.listFavoritesByUserStmt != nil {
		if cerr := q.listFavoritesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFavoritesByUserStmt: %w", cerr)
		}
	}
	if q.markEmailVerificationAsUsedStmt != nil {
		if cerr := q.markEmailVerificationAsUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEmailVerificationAsUsedStmt: %w", cerr)
		}
	}
	if q.removeFavoriteStmt != nil {
		if cerr := q.removeFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeFavoriteStmt: %w", cerr)
		}
	}
	if q.searchScholarshipsStmt != nil {
		if cerr := q.searchScholarshipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchScholarshipsStmt: %w", cerr)
		}
	}
	if q.searchScholarshipsByProgramsStmt != nil {
		if cerr := q.searchScholarshipsByProgramsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchScholarshipsByProgramsStmt: %w", cerr)
		}
	}
	if q.updateFavoriteStatusStmt != nil {
		if cerr := q.updateFavoriteStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFavoriteStatusStmt: %w", cerr)
		}
	}
	if q.updateOAuthLoginStmt != nil {
		if cerr := q.updateOAuthLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOAuthLoginStmt: %w", cerr)
		}
	}
	if q.updateScholarshipStmt != nil {
		if cerr := q.updateScholarshipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateScholarshipStmt: %w", cerr)
		}
	}
	if q.updateScholarshipJSONBStmt != nil {
		if cerr := q.updateScholarshipJSONBStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateScholarshipJSONBStmt: %w", cerr)
		}
	}
	if q.updateStudentProfileStmt != nil {
		if cerr := q.updateStudentProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStudentProfileStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	if q.upsertOauthLoginStmt != nil {
		if cerr := q.upsertOauthLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOauthLoginStmt: %w", cerr)
		}
	}
	if q.verifyUserEmailStmt != nil {
		if cerr := q.verifyUserEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyUserEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                       DBTX
	tx                                       *sql.Tx
	addFavoriteStmt                          *sql.Stmt
	adminUpdateUserTOTPSecretStmt            *sql.Stmt
	checkUserExistByEmailStmt                *sql.Stmt
	cleanupExpiredVerificationsStmt          *sql.Stmt
	createEmailVerificationStmt              *sql.Stmt
	createOAuthLoginStmt                     *sql.Stmt
	createScholarshipStmt                    *sql.Stmt
	createScholarshipWithDetailsStmt         *sql.Stmt
	createStudentProfileStmt                 *sql.Stmt
	createUserStmt                           *sql.Stmt
	deleteEmailVerificationsByUserIDStmt     *sql.Stmt
	deleteExpiredVerificationsStmt           *sql.Stmt
	deleteOAuthLoginStmt                     *sql.Stmt
	deleteScholarshipByIDStmt                *sql.Stmt
	deleteStudentProfileStmt                 *sql.Stmt
	enableAdmin2FAStmt                       *sql.Stmt
	getActiveScholarshipsStmt                *sql.Stmt
	getAdminByEmailStmt                      *sql.Stmt
	getAdminByIDStmt                         *sql.Stmt
	getAdminByIDOrEmailStmt                  *sql.Stmt
	getAllScholarshipsStmt                   *sql.Stmt
	getEmailVerificationByTokenStmt          *sql.Stmt
	getEmailVerificationByUserIDStmt         *sql.Stmt
	getLatestVerificationByEmailStmt         *sql.Stmt
	getOAuthLoginByProviderStmt              *sql.Stmt
	getOAuthLoginsByUserIDStmt               *sql.Stmt
	getRemindersForTodayStmt                 *sql.Stmt
	getScholarshipByIDStmt                   *sql.Stmt
	getScholarshipsByIDsStmt                 *sql.Stmt
	getScholarshipsByInstitutionCodeLikeStmt *sql.Stmt
	getStudentProfileStmt                    *sql.Stmt
	getUnverifiedUserByEmailStmt             *sql.Stmt
	getUserByEmailStmt                       *sql.Stmt
	getUserByIDStmt                          *sql.Stmt
	getUserByIDOrEmailStmt                   *sql.Stmt
	getUserByOAuthProviderStmt               *sql.Stmt
	getUserWithStudentProfileStmt            *sql.Stmt
	listFavoritesByUserStmt                  *sql.Stmt
	markEmailVerificationAsUsedStmt          *sql.Stmt
	removeFavoriteStmt                       *sql.Stmt
	searchScholarshipsStmt                   *sql.Stmt
	searchScholarshipsByProgramsStmt         *sql.Stmt
	updateFavoriteStatusStmt                 *sql.Stmt
	updateOAuthLoginStmt                     *sql.Stmt
	updateScholarshipStmt                    *sql.Stmt
	updateScholarshipJSONBStmt               *sql.Stmt
	updateStudentProfileStmt                 *sql.Stmt
	updateUserProfileStmt                    *sql.Stmt
	upsertOauthLoginStmt                     *sql.Stmt
	verifyUserEmailStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                       tx,
		tx:                                       tx,
		addFavoriteStmt:                          q.addFavoriteStmt,
		adminUpdateUserTOTPSecretStmt:            q.adminUpdateUserTOTPSecretStmt,
		checkUserExistByEmailStmt:                q.checkUserExistByEmailStmt,
		cleanupExpiredVerificationsStmt:          q.cleanupExpiredVerificationsStmt,
		createEmailVerificationStmt:              q.createEmailVerificationStmt,
		createOAuthLoginStmt:                     q.createOAuthLoginStmt,
		createScholarshipStmt:                    q.createScholarshipStmt,
		createScholarshipWithDetailsStmt:         q.createScholarshipWithDetailsStmt,
		createStudentProfileStmt:                 q.createStudentProfileStmt,
		createUserStmt:                           q.createUserStmt,
		deleteEmailVerificationsByUserIDStmt:     q.deleteEmailVerificationsByUserIDStmt,
		deleteExpiredVerificationsStmt:           q.deleteExpiredVerificationsStmt,
		deleteOAuthLoginStmt:                     q.deleteOAuthLoginStmt,
		deleteScholarshipByIDStmt:                q.deleteScholarshipByIDStmt,
		deleteStudentProfileStmt:                 q.deleteStudentProfileStmt,
		enableAdmin2FAStmt:                       q.enableAdmin2FAStmt,
		getActiveScholarshipsStmt:                q.getActiveScholarshipsStmt,
		getAdminByEmailStmt:                      q.getAdminByEmailStmt,
		getAdminByIDStmt:                         q.getAdminByIDStmt,
		getAdminByIDOrEmailStmt:                  q.getAdminByIDOrEmailStmt,
		getAllScholarshipsStmt:                   q.getAllScholarshipsStmt,
		getEmailVerificationByTokenStmt:          q.getEmailVerificationByTokenStmt,
		getEmailVerificationByUserIDStmt:         q.getEmailVerificationByUserIDStmt,
		getLatestVerificationByEmailStmt:         q.getLatestVerificationByEmailStmt,
		getOAuthLoginByProviderStmt:              q.getOAuthLoginByProviderStmt,
		getOAuthLoginsByUserIDStmt:               q.getOAuthLoginsByUserIDStmt,
		getRemindersForTodayStmt:                 q.getRemindersForTodayStmt,
		getScholarshipByIDStmt:                   q.getScholarshipByIDStmt,
		getScholarshipsByIDsStmt:                 q.getScholarshipsByIDsStmt,
		getScholarshipsByInstitutionCodeLikeStmt: q.getScholarshipsByInstitutionCodeLikeStmt,
		getStudentProfileStmt:                    q.getStudentProfileStmt,
		getUnverifiedUserByEmailStmt:             q.getUnverifiedUserByEmailStmt,
		getUserByEmailStmt:                       q.getUserByEmailStmt,
		getUserByIDStmt:                          q.getUserByIDStmt,
		getUserByIDOrEmailStmt:                   q.getUserByIDOrEmailStmt,
		getUserByOAuthProviderStmt:               q.getUserByOAuthProviderStmt,
		getUserWithStudentProfileStmt:            q.getUserWithStudentProfileStmt,
		listFavoritesByUserStmt:                  q.listFavoritesByUserStmt,
		markEmailVerificationAsUsedStmt:          q.markEmailVerificationAsUsedStmt,
		removeFavoriteStmt:                       q.removeFavoriteStmt,
		searchScholarshipsStmt:                   q.searchScholarshipsStmt,
		searchScholarshipsByProgramsStmt:         q.searchScholarshipsByProgramsStmt,
		updateFavoriteStatusStmt:                 q.updateFavoriteStatusStmt,
		updateOAuthLoginStmt:                     q.updateOAuthLoginStmt,
		updateScholarshipStmt:                    q.updateScholarshipStmt,
		updateScholarshipJSONBStmt:               q.updateScholarshipJSONBStmt,
		updateStudentProfileStmt:                 q.updateStudentProfileStmt,
		updateUserProfileStmt:                    q.updateUserProfileStmt,
		upsertOauthLoginStmt:                     q.upsertOauthLoginStmt,
		verifyUserEmailStmt:                      q.verifyUserEmailStmt,
	}
}
