// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: EmailVerification.sql

package db

import (
	"context"
	"time"
)

const cleanupExpiredVerifications = `-- name: CleanupExpiredVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredVerifications(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanupExpiredVerificationsStmt, cleanupExpiredVerifications)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, verified_at, created_at, updated_at
`

type CreateEmailVerificationParams struct {
	UserID    int32     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.queryRow(ctx, q.createEmailVerificationStmt, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailVerificationsByUserID = `-- name: DeleteEmailVerificationsByUserID :exec
DELETE FROM email_verifications
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationsByUserID(ctx context.Context, userID int32) error {
	_, err := q.exec(ctx, q.deleteEmailVerificationsByUserIDStmt, deleteEmailVerificationsByUserID, userID)
	return err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, user_id, token, expires_at, verified_at, created_at, updated_at FROM email_verifications
WHERE token = $1 AND verified_at IS NULL
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.queryRow(ctx, q.getEmailVerificationByTokenStmt, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailVerificationByUserID = `-- name: GetEmailVerificationByUserID :one
SELECT id, user_id, token, expires_at, verified_at, created_at, updated_at FROM email_verifications
WHERE user_id = $1 AND verified_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetEmailVerificationByUserID(ctx context.Context, userID int32) (EmailVerification, error) {
	row := q.queryRow(ctx, q.getEmailVerificationByUserIDStmt, getEmailVerificationByUserID, userID)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerificationAsUsed = `-- name: MarkEmailVerificationAsUsed :exec
UPDATE email_verifications
SET verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationAsUsed(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.markEmailVerificationAsUsedStmt, markEmailVerificationAsUsed, id)
	return err
}
