// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: FavoriteScholarships.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorite_scholarships (user_id, scholarship_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID        int64 `json:"user_id"`
	ScholarshipID int64 `json:"scholarship_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.exec(ctx, q.addFavoriteStmt, addFavorite, arg.UserID, arg.ScholarshipID)
	return err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT s.id, s.title, s.provider, s.description, s.institution_info, s.requirements, s.extra_notes, s.deadline_end, s.official_link, s.photo_url, s.created_at, s.updated_at
FROM favorite_scholarships f
JOIN scholarships s ON f.scholarship_id = s.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

func (q *Queries) ListFavoritesByUser(ctx context.Context, userID int64) ([]Scholarship, error) {
	rows, err := q.query(ctx, q.listFavoritesByUserStmt, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scholarship
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorite_scholarships
WHERE user_id = $1 AND scholarship_id = $2
`

type RemoveFavoriteParams struct {
	UserID        int64 `json:"user_id"`
	ScholarshipID int64 `json:"scholarship_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.exec(ctx, q.removeFavoriteStmt, removeFavorite, arg.UserID, arg.ScholarshipID)
	return err
}
