// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: FavoriteScholarships.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorite_scholarships (user_id, scholarship_id)
VALUES ($1, $2)
ON CONFLICT (user_id, scholarship_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID        int64 `json:"user_id"`
	ScholarshipID int64 `json:"scholarship_id"`
}

// Add a favorite
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.exec(ctx, q.addFavoriteStmt, addFavorite, arg.UserID, arg.ScholarshipID)
	return err
}

const getRemindersForToday = `-- name: GetRemindersForToday :many
SELECT 
    u.fullname,
    u.email,
    s.title,
    s.description,
    s.deadline_end,
    s.official_link,
    fs.is_reminder
FROM favorite_scholarships fs
LEFT JOIN users u 
    ON u.id = fs.user_id
LEFT JOIN scholarships s
    ON s.id = fs.scholarship_id
`

type GetRemindersForTodayRow struct {
	Fullname     sql.NullString `json:"fullname"`
	Email        sql.NullString `json:"email"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	DeadlineEnd  sql.NullTime   `json:"deadline_end"`
	OfficialLink sql.NullString `json:"official_link"`
	IsReminder   sql.NullBool   `json:"is_reminder"`
}

func (q *Queries) GetRemindersForToday(ctx context.Context) ([]GetRemindersForTodayRow, error) {
	rows, err := q.query(ctx, q.getRemindersForTodayStmt, getRemindersForToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRemindersForTodayRow
	for rows.Next() {
		var i GetRemindersForTodayRow
		if err := rows.Scan(
			&i.Fullname,
			&i.Email,
			&i.Title,
			&i.Description,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.IsReminder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT 
    s.id AS scholarship_id,
    s.title,
    s.provider,
    s.description,
    s.institution_info,
    s.requirements,
    s.extra_notes,
    s.deadline_end,
    s.official_link,
    s.categories,
    s.photo_url,
    s.created_at
FROM favorite_scholarships f
JOIN scholarships s ON f.scholarship_id = s.id
WHERE f.user_id = $1 AND f.is_favorite = TRUE
ORDER BY f.created_at DESC
`

type ListFavoritesByUserRow struct {
	ScholarshipID   int32                 `json:"scholarship_id"`
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	Categories      pqtype.NullRawMessage `json:"categories"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

// List all favorites for a user (joined with scholarships)
func (q *Queries) ListFavoritesByUser(ctx context.Context, userID int64) ([]ListFavoritesByUserRow, error) {
	rows, err := q.query(ctx, q.listFavoritesByUserStmt, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesByUserRow
	for rows.Next() {
		var i ListFavoritesByUserRow
		if err := rows.Scan(
			&i.ScholarshipID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.Categories,
			&i.PhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorite_scholarships
WHERE user_id = $1 AND scholarship_id = $2
`

type RemoveFavoriteParams struct {
	UserID        int64 `json:"user_id"`
	ScholarshipID int64 `json:"scholarship_id"`
}

// Remove a favorite
func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.exec(ctx, q.removeFavoriteStmt, removeFavorite, arg.UserID, arg.ScholarshipID)
	return err
}

const updateFavoriteStatus = `-- name: UpdateFavoriteStatus :exec
UPDATE favorite_scholarships
SET is_favorite = $1
WHERE user_id = $2
  AND scholarship_id = $3
`

type UpdateFavoriteStatusParams struct {
	IsFavorite    bool  `json:"is_favorite"`
	UserID        int64 `json:"user_id"`
	ScholarshipID int64 `json:"scholarship_id"`
}

func (q *Queries) UpdateFavoriteStatus(ctx context.Context, arg UpdateFavoriteStatusParams) error {
	_, err := q.exec(ctx, q.updateFavoriteStatusStmt, updateFavoriteStatus, arg.IsFavorite, arg.UserID, arg.ScholarshipID)
	return err
}
