// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetScholarship.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const getAllScholarships = `-- name: GetAllScholarships :many
SELECT 
    id,
    title,
    provider,
    description,
    institution_info,
    requirements,
    extra_notes,
    deadline_end,
    official_link,
    photo_url,
    created_at
FROM scholarships
ORDER BY created_at DESC
`

type GetAllScholarshipsRow struct {
	ID              int32                 `json:"id"`
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

func (q *Queries) GetAllScholarships(ctx context.Context) ([]GetAllScholarshipsRow, error) {
	rows, err := q.query(ctx, q.getAllScholarshipsStmt, getAllScholarships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllScholarshipsRow
	for rows.Next() {
		var i GetAllScholarshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.PhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScholarshipByID = `-- name: GetScholarshipByID :one
SELECT 
    id AS scholarship_id,
    title,
    provider,
    description,
    institution_info,
    requirements,
    extra_notes,
    deadline_end,
    official_link,
    photo_url,
    created_at
FROM scholarships
WHERE id = $1
`

type GetScholarshipByIDRow struct {
	ScholarshipID   int32                 `json:"scholarship_id"`
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

func (q *Queries) GetScholarshipByID(ctx context.Context, id int32) (GetScholarshipByIDRow, error) {
	row := q.queryRow(ctx, q.getScholarshipByIDStmt, getScholarshipByID, id)
	var i GetScholarshipByIDRow
	err := row.Scan(
		&i.ScholarshipID,
		&i.Title,
		&i.Provider,
		&i.Description,
		&i.InstitutionInfo,
		&i.Requirements,
		&i.ExtraNotes,
		&i.DeadlineEnd,
		&i.OfficialLink,
		&i.PhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getScholarshipsByIDs = `-- name: GetScholarshipsByIDs :many
SELECT id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, created_at, updated_at, institution_code
FROM scholarships
WHERE id = ANY($1::int[])
`

func (q *Queries) GetScholarshipsByIDs(ctx context.Context, dollar_1 []int32) ([]Scholarship, error) {
	rows, err := q.query(ctx, q.getScholarshipsByIDsStmt, getScholarshipsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scholarship
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstitutionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScholarshipsByInstitutionCodeLike = `-- name: GetScholarshipsByInstitutionCodeLike :many
SELECT id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, created_at, updated_at, institution_code
FROM scholarships
WHERE institution_code ILIKE '%' || $1 || '%'
`

func (q *Queries) GetScholarshipsByInstitutionCodeLike(ctx context.Context, code sql.NullString) ([]Scholarship, error) {
	rows, err := q.query(ctx, q.getScholarshipsByInstitutionCodeLikeStmt, getScholarshipsByInstitutionCodeLike, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scholarship
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstitutionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScholarships = `-- name: SearchScholarships :many
SELECT id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, created_at, updated_at, institution_code
FROM scholarships
WHERE (institution_code ILIKE '%' || $1 || '%' OR $1 IS NULL)
  AND (institution_info->0->>'institution' ILIKE '%' || $2 || '%' OR $2 IS NULL)
  AND (
        EXISTS (
            SELECT 1 FROM jsonb_array_elements(institution_info->0->'programs_offered') AS p
            WHERE p->>0 ILIKE '%' || $3 || '%'
        ) OR $3 IS NULL
      )
`

type SearchScholarshipsParams struct {
	Code    sql.NullString `json:"code"`
	Name    sql.NullString `json:"name"`
	Program sql.NullString `json:"program"`
}

func (q *Queries) SearchScholarships(ctx context.Context, arg SearchScholarshipsParams) ([]Scholarship, error) {
	rows, err := q.query(ctx, q.searchScholarshipsStmt, searchScholarships, arg.Code, arg.Name, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scholarship
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Provider,
			&i.Description,
			&i.InstitutionInfo,
			&i.Requirements,
			&i.ExtraNotes,
			&i.DeadlineEnd,
			&i.OfficialLink,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstitutionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScholarship = `-- name: UpdateScholarship :one
UPDATE scholarships SET
    title = $2,
    provider = $3,
    description = $4,
    institution_info = $5,
    requirements = $6,
    extra_notes = $7,
    deadline_end = $8,
    official_link = $9,
    photo_url = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, created_at, updated_at, institution_code
`

type UpdateScholarshipParams struct {
	ID              int32                 `json:"id"`
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
}

func (q *Queries) UpdateScholarship(ctx context.Context, arg UpdateScholarshipParams) (Scholarship, error) {
	row := q.queryRow(ctx, q.updateScholarshipStmt, updateScholarship,
		arg.ID,
		arg.Title,
		arg.Provider,
		arg.Description,
		arg.InstitutionInfo,
		arg.Requirements,
		arg.ExtraNotes,
		arg.DeadlineEnd,
		arg.OfficialLink,
		arg.PhotoUrl,
	)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Provider,
		&i.Description,
		&i.InstitutionInfo,
		&i.Requirements,
		&i.ExtraNotes,
		&i.DeadlineEnd,
		&i.OfficialLink,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstitutionCode,
	)
	return i, err
}

const updateScholarshipJSONB = `-- name: UpdateScholarshipJSONB :one
UPDATE scholarships SET
    institution_info = COALESCE($2, institution_info),
    requirements = COALESCE($3, requirements),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, provider, description, institution_info, requirements, extra_notes, deadline_end, official_link, photo_url, created_at, updated_at, institution_code
`

type UpdateScholarshipJSONBParams struct {
	ID              int32                 `json:"id"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
}

func (q *Queries) UpdateScholarshipJSONB(ctx context.Context, arg UpdateScholarshipJSONBParams) (Scholarship, error) {
	row := q.queryRow(ctx, q.updateScholarshipJSONBStmt, updateScholarshipJSONB, arg.ID, arg.InstitutionInfo, arg.Requirements)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Provider,
		&i.Description,
		&i.InstitutionInfo,
		&i.Requirements,
		&i.ExtraNotes,
		&i.DeadlineEnd,
		&i.OfficialLink,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstitutionCode,
	)
	return i, err
}
