// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserProfile.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getUserWithProfile = `-- name: GetUserWithProfile :one
SELECT 
    u.id,
    u.fullname,
    u.email,
    u.phone_number,
    u.high_school,
    u.grade_level,
    u.diploma_year,
    s.diploma_grade,
    s.select_majors,
    s.created_at AS profile_created_at,
    s.updated_at AS profile_updated_at
FROM users u
LEFT JOIN student_profiles s ON s.student_id = u.id
WHERE u.id = $1 OR u.email = $2
`

type GetUserWithProfileParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

type GetUserWithProfileRow struct {
	ID               int32                 `json:"id"`
	Fullname         sql.NullString        `json:"fullname"`
	Email            string                `json:"email"`
	PhoneNumber      sql.NullString        `json:"phone_number"`
	HighSchool       sql.NullString        `json:"high_school"`
	GradeLevel       sql.NullInt32         `json:"grade_level"`
	DiplomaYear      sql.NullInt32         `json:"diploma_year"`
	DiplomaGrade     NullDiplomaGrade      `json:"diploma_grade"`
	SelectMajors     pqtype.NullRawMessage `json:"select_majors"`
	ProfileCreatedAt sql.NullTime          `json:"profile_created_at"`
	ProfileUpdatedAt sql.NullTime          `json:"profile_updated_at"`
}

func (q *Queries) GetUserWithProfile(ctx context.Context, arg GetUserWithProfileParams) (GetUserWithProfileRow, error) {
	row := q.queryRow(ctx, q.getUserWithProfileStmt, getUserWithProfile, arg.ID, arg.Email)
	var i GetUserWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PhoneNumber,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.DiplomaGrade,
		&i.SelectMajors,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}
