// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUser.sql

package db

import (
	"context"
)

const getUserByIDOrEmail = `-- name: GetUserByIDOrEmail :one
SELECT 
    id,
    fullname,
    email,
    password_hash,
    role,
    phone_number,
    high_school,
    grade_level,
    diploma_year,
    created_at,
    updated_at
FROM users
WHERE id = $1 OR email = $2
`

type GetUserByIDOrEmailParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) GetUserByIDOrEmail(ctx context.Context, arg GetUserByIDOrEmailParams) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDOrEmailStmt, getUserByIDOrEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.PhoneNumber,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
