// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	ID           int32
	Fullname     string
	Email        string
	PasswordHash sql.NullString
	Role         interface{}
	PhoneNumber  sql.NullString
	HighSchool   sql.NullString
	GradeLevel   sql.NullInt32
	DiplomaYear  sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
