// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	ID           int32          `json:"id"`
	Fullname     sql.NullString `json:"fullname"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	TotpSecret   sql.NullString `json:"totp_secret"`
	IsTwoFactor  bool           `json:"is_two_factor"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type EmailVerification struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	Token      string       `json:"token"`
	ExpiresAt  time.Time    `json:"expires_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type FavoriteScholarship struct {
	UserID        int64        `json:"user_id"`
	ScholarshipID int64        `json:"scholarship_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	IsReminder    sql.NullBool `json:"is_reminder"`
	IsFavorite    bool         `json:"is_favorite"`
}

type OauthLogin struct {
	ID             int32          `json:"id"`
	UserID         sql.NullInt32  `json:"user_id"`
	Provider       interface{}    `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	AccessToken    string         `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Scholarship struct {
	ID              int32                 `json:"id"`
	Title           string                `json:"title"`
	Provider        string                `json:"provider"`
	Description     sql.NullString        `json:"description"`
	InstitutionInfo pqtype.NullRawMessage `json:"institution_info"`
	Requirements    pqtype.NullRawMessage `json:"requirements"`
	ExtraNotes      sql.NullString        `json:"extra_notes"`
	DeadlineEnd     sql.NullTime          `json:"deadline_end"`
	OfficialLink    sql.NullString        `json:"official_link"`
	PhotoUrl        sql.NullString        `json:"photo_url"`
	Categories      pqtype.NullRawMessage `json:"categories"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
	InstitutionCode sql.NullString        `json:"institution_code"`
}

type StudentProfile struct {
	ID           int32                 `json:"id"`
	StudentID    int32                 `json:"student_id"`
	HighSchool   sql.NullString        `json:"high_school"`
	GradeLevel   sql.NullString        `json:"grade_level"`
	DiplomaYear  sql.NullInt32         `json:"diploma_year"`
	DiplomaGrade sql.NullString        `json:"diploma_grade"`
	SelectMajors pqtype.NullRawMessage `json:"select_majors"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type User struct {
	ID            int32          `json:"id"`
	Fullname      sql.NullString `json:"fullname"`
	Email         string         `json:"email"`
	PasswordHash  sql.NullString `json:"password_hash"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	EmailVerified sql.NullBool   `json:"email_verified"`
}
