// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_logins.sql

package db

import (
	"context"
	"database/sql"
)

const upsertOauthLogin = `-- name: UpsertOauthLogin :one
INSERT INTO oauth_logins (user_id, provider, provider_user_id, access_token, refresh_token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET
    user_id = EXCLUDED.user_id,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, created_at, updated_at
`

type UpsertOauthLoginParams struct {
	UserID         sql.NullInt32
	Provider       OauthProvider
	ProviderUserID string
	AccessToken    string
	RefreshToken   sql.NullString
}

func (q *Queries) UpsertOauthLogin(ctx context.Context, arg UpsertOauthLoginParams) (OauthLogin, error) {
	row := q.db.QueryRowContext(ctx, upsertOauthLogin,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
	)
	var i OauthLogin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
