// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: StudentProfile.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createStudentProfile = `-- name: CreateStudentProfile :one
INSERT INTO student_profiles (
    student_id,
    high_school,
    grade_level,
    diploma_year,
    diploma_grade,
    select_majors
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, high_school, grade_level, diploma_year, diploma_grade, select_majors, created_at, updated_at
`

type CreateStudentProfileParams struct {
	StudentID    int32                 `json:"student_id"`
	HighSchool   sql.NullString        `json:"high_school"`
	GradeLevel   sql.NullString        `json:"grade_level"`
	DiplomaYear  sql.NullInt32         `json:"diploma_year"`
	DiplomaGrade sql.NullString        `json:"diploma_grade"`
	SelectMajors pqtype.NullRawMessage `json:"select_majors"`
}

func (q *Queries) CreateStudentProfile(ctx context.Context, arg CreateStudentProfileParams) (StudentProfile, error) {
	row := q.queryRow(ctx, q.createStudentProfileStmt, createStudentProfile,
		arg.StudentID,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
		arg.DiplomaGrade,
		arg.SelectMajors,
	)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.DiplomaGrade,
		&i.SelectMajors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudentProfile = `-- name: DeleteStudentProfile :exec
DELETE FROM student_profiles WHERE student_id = $1
`

func (q *Queries) DeleteStudentProfile(ctx context.Context, studentID int32) error {
	_, err := q.exec(ctx, q.deleteStudentProfileStmt, deleteStudentProfile, studentID)
	return err
}

const getStudentProfile = `-- name: GetStudentProfile :one
SELECT id, student_id, high_school, grade_level, diploma_year, diploma_grade, select_majors, created_at, updated_at
FROM student_profiles
WHERE student_id = $1
`

func (q *Queries) GetStudentProfile(ctx context.Context, studentID int32) (StudentProfile, error) {
	row := q.queryRow(ctx, q.getStudentProfileStmt, getStudentProfile, studentID)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.DiplomaGrade,
		&i.SelectMajors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithStudentProfile = `-- name: GetUserWithStudentProfile :one
SELECT 
    u.id as user_id,
    u.fullname,
    u.email,               
    sp.high_school,
    sp.grade_level,
    sp.diploma_year,
    sp.diploma_grade,
    sp.select_majors,
    sp.created_at as profile_created_at,
    sp.updated_at as profile_updated_at
FROM users u
LEFT JOIN student_profiles sp ON u.id = sp.student_id
WHERE u.id = $1
`

type GetUserWithStudentProfileRow struct {
	UserID           int32                 `json:"user_id"`
	Fullname         sql.NullString        `json:"fullname"`
	Email            string                `json:"email"`
	HighSchool       sql.NullString        `json:"high_school"`
	GradeLevel       sql.NullString        `json:"grade_level"`
	DiplomaYear      sql.NullInt32         `json:"diploma_year"`
	DiplomaGrade     sql.NullString        `json:"diploma_grade"`
	SelectMajors     pqtype.NullRawMessage `json:"select_majors"`
	ProfileCreatedAt sql.NullTime          `json:"profile_created_at"`
	ProfileUpdatedAt sql.NullTime          `json:"profile_updated_at"`
}

func (q *Queries) GetUserWithStudentProfile(ctx context.Context, id int32) (GetUserWithStudentProfileRow, error) {
	row := q.queryRow(ctx, q.getUserWithStudentProfileStmt, getUserWithStudentProfile, id)
	var i GetUserWithStudentProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Fullname,
		&i.Email,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.DiplomaGrade,
		&i.SelectMajors,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const updateStudentProfile = `-- name: UpdateStudentProfile :one
UPDATE student_profiles 
SET 
    high_school = $2,
    grade_level = $3,
    diploma_year = $4,
    diploma_grade = $5,
    select_majors = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE student_id = $1
RETURNING id, student_id, high_school, grade_level, diploma_year, diploma_grade, select_majors, created_at, updated_at
`

type UpdateStudentProfileParams struct {
	StudentID    int32                 `json:"student_id"`
	HighSchool   sql.NullString        `json:"high_school"`
	GradeLevel   sql.NullString        `json:"grade_level"`
	DiplomaYear  sql.NullInt32         `json:"diploma_year"`
	DiplomaGrade sql.NullString        `json:"diploma_grade"`
	SelectMajors pqtype.NullRawMessage `json:"select_majors"`
}

func (q *Queries) UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) (StudentProfile, error) {
	row := q.queryRow(ctx, q.updateStudentProfileStmt, updateStudentProfile,
		arg.StudentID,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
		arg.DiplomaGrade,
		arg.SelectMajors,
	)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.DiplomaGrade,
		&i.SelectMajors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
