// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateUserProfile.sql

package db

import (
	"context"
	"database/sql"
)

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET
    fullname = COALESCE($1, fullname),
    phone_number = COALESCE($2, phone_number),
    high_school = COALESCE($3, high_school),
    grade_level = COALESCE($4, grade_level),
    diploma_year = COALESCE($5, diploma_year),
    updated_at = NOW()
WHERE id = $6
`

type UpdateUserProfileParams struct {
	Fullname    sql.NullString `json:"fullname"`
	PhoneNumber sql.NullString `json:"phone_number"`
	HighSchool  sql.NullString `json:"high_school"`
	GradeLevel  sql.NullInt32  `json:"grade_level"`
	DiplomaYear sql.NullInt32  `json:"diploma_year"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.exec(ctx, q.updateUserProfileStmt, updateUserProfile,
		arg.Fullname,
		arg.PhoneNumber,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
		arg.ID,
	)
	return err
}
