// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateUserProfile.sql

package db

import (
	"context"
	"database/sql"
)

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET fullname = COALESCE($1, fullname),
    phone_number = COALESCE($2, phone_number)
WHERE id = $3
RETURNING id, fullname, email, password_hash, phone_number, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Fullname    sql.NullString `json:"fullname"`
	PhoneNumber sql.NullString `json:"phone_number"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile, arg.Fullname, arg.PhoneNumber, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
