// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateStudentProfile.sql

package db

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const updateStudentProfile = `-- name: UpdateStudentProfile :exec
UPDATE student_profiles
SET
    diploma_grade = COALESCE($1, diploma_grade),
    select_majors = COALESCE($2, select_majors),
    updated_at = NOW()
WHERE student_id = $3
`

type UpdateStudentProfileParams struct {
	DiplomaGrade NullDiplomaGrade      `json:"diploma_grade"`
	SelectMajors pqtype.NullRawMessage `json:"select_majors"`
	StudentID    int32                 `json:"student_id"`
}

func (q *Queries) UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) error {
	_, err := q.exec(ctx, q.updateStudentProfileStmt, updateStudentProfile, arg.DiplomaGrade, arg.SelectMajors, arg.StudentID)
	return err
}
