// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateUserProfile.sql

package db

import (
	"context"
	"database/sql"
)

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users 
SET fullname = $2, phone_number = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, fullname, email, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          int32          `json:"id"`
	Fullname    sql.NullString `json:"fullname"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

type UpdateUserProfileRow struct {
	ID        int32          `json:"id"`
	Fullname  sql.NullString `json:"fullname"`
	Email     string         `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile, arg.ID, arg.Fullname, arg.PhoneNumber)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
