// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (fullname, email, password_hash, phone_number, high_school, grade_level, diploma_year)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, fullname, email, created_at, updated_at
`

type CreateUserParams struct {
	Fullname     string
	Email        string
	PasswordHash sql.NullString
	PhoneNumber  sql.NullString
	HighSchool   sql.NullString
	GradeLevel   sql.NullInt32
	DiplomaYear  sql.NullInt32
}

type CreateUserRow struct {
	ID        int32
	Fullname  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Fullname,
		arg.Email,
		arg.PasswordHash,
		arg.PhoneNumber,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, fullname, email, password_hash, role, created_at, updated_at
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID           int32
	Fullname     string
	Email        string
	PasswordHash sql.NullString
	Role         interface{}
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET fullname = $2,
    phone_number = $3,
    high_school = $4,
    grade_level = $5,
    diploma_year = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, fullname, email, phone_number, high_school, grade_level, diploma_year, role, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          int32
	Fullname    string
	PhoneNumber sql.NullString
	HighSchool  sql.NullString
	GradeLevel  sql.NullInt32
	DiplomaYear sql.NullInt32
}

type UpdateUserProfileRow struct {
	ID          int32
	Fullname    string
	Email       string
	PhoneNumber sql.NullString
	HighSchool  sql.NullString
	GradeLevel  sql.NullInt32
	DiplomaYear sql.NullInt32
	Role        interface{}
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.Fullname,
		arg.PhoneNumber,
		arg.HighSchool,
		arg.GradeLevel,
		arg.DiplomaYear,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.PhoneNumber,
		&i.HighSchool,
		&i.GradeLevel,
		&i.DiplomaYear,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
