// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UserTotp.sql

package db

import (
	"context"
	"database/sql"
)

const adminUpdateUserTOTPSecret = `-- name: AdminUpdateUserTOTPSecret :exec
UPDATE admins
SET totp_secret = $2
WHERE id = $1
`

type AdminUpdateUserTOTPSecretParams struct {
	ID         int32          `json:"id"`
	TotpSecret sql.NullString `json:"totp_secret"`
}

// description: Admin-only query to update a user's TOTP secret
func (q *Queries) AdminUpdateUserTOTPSecret(ctx context.Context, arg AdminUpdateUserTOTPSecretParams) error {
	_, err := q.exec(ctx, q.adminUpdateUserTOTPSecretStmt, adminUpdateUserTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const enableAdmin2FA = `-- name: EnableAdmin2FA :exec
UPDATE admins
SET is_two_factor = TRUE
WHERE id = $1
`

func (q *Queries) EnableAdmin2FA(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.enableAdmin2FAStmt, enableAdmin2FA, id)
	return err
}
