// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://eduvsion.example.com/terms",
        "contact": {
            "name": "EduVision Support",
            "url": "https://eduvsion.example.com/support",
            "email": "support@eduvsion.example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login into user account",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user profile information",
                "responses": {
                    "200": {
                        "description": "Fetch User successfully",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create a new student account with email, password, and profile info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Registration successful",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/update-profile": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user and profile information",
                "parameters": [
                    {
                        "description": "Update user profile",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update User Profile successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIUpdateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "supersecret"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.RegisterInput": {
            "type": "object",
            "properties": {
                "diploma_year": {
                    "type": "integer",
                    "example": 2025
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "fullname": {
                    "type": "string",
                    "example": "John Doe"
                },
                "grade_level": {
                    "type": "integer",
                    "example": 12
                },
                "high_school": {
                    "type": "string",
                    "example": "Springfield High"
                },
                "password": {
                    "type": "string",
                    "example": "SuperSecret123"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+855-17-345-6790"
                }
            }
        },
        "models.StudentProfile": {
            "type": "object",
            "properties": {
                "diploma_grade": {
                    "type": "string",
                    "example": "A+"
                },
                "select_majors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"Computer Science\"",
                        " \"Law\"]"
                    ]
                }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "diploma_grade": {
                    "type": "string"
                },
                "diploma_year": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "grade_level": {
                    "type": "integer"
                },
                "high_school": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "select_majors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.UserProfileResponse": {
            "type": "object",
            "properties": {
                "diploma_year": {
                    "type": "integer",
                    "example": 2023
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "fullname": {
                    "type": "string",
                    "example": "John Doe"
                },
                "grade_level": {
                    "type": "integer",
                    "example": 12
                },
                "high_school": {
                    "type": "string",
                    "example": "ABC High School"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "phone_number": {
                    "type": "string",
                    "example": "123-456-7890"
                },
                "profile_created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "profile_updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "role": {
                    "type": "string",
                    "example": "student"
                },
                "student_profile": {
                    "$ref": "#/definitions/models.StudentProfile"
                }
            }
        },
        "utils.APIResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "utils.APIUpdateResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "User profile updated successfully"
                },
                "status": {
                    "type": "string",
                    "example": "200"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "status": {
                    "type": "string",
                    "example": "200"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "EduVision Scholarship Portal API",
	Description:      "This API allows managing student profiles, authentication, and scholarship applications for the EduVision portal.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
