// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1": {
            "get": {
                "description": "Returns the home page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "Home",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register new user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.RegisterModel": {
            "type": "object",
            "required": [
                "fullname",
                "email",
                "high_school",
                "password",
                "phone_number"
            ],
            "properties": {
                "fullname": {
                    "type": "string",
                    "example": "John Doe"
                },
                "diploma_grade": {
                    "type": "string",
                    "example": "A"
                },
                "diploma_year": {
                    "type": "integer",
                    "example": 2025
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "grade_level": {
                    "type": "integer",
                    "example": 12
                },
                "high_school": {
                    "type": "string",
                    "example": "Springfield High"
                },
                "password": {
                    "type": "string",
                    "example": "supersecret"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+15555555555"
                },
                "role": {
                    "type": "string",
                    "example": "student"
                }
            }
        },
        "models.RegisterResponse": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string",
                    "example": "John Doe"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-09-04T15:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-09-04T15:45:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EduVision for Scholarship Portal API",
	Description:      "API documentation for EduVision Scholarship Portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
