basePath: /api/v1
definitions:
  models.LoginRequest:
    properties:
      email:
        example: johndoe@example.com
        type: string
      password:
        example: supersecret
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  models.RegisterInput:
    properties:
      diploma_year:
        example: 2025
        type: integer
      email:
        example: john.doe@example.com
        type: string
      fullname:
        example: John Doe
        type: string
      grade_level:
        example: 12
        type: integer
      high_school:
        example: Springfield High
        type: string
      password:
        example: SuperSecret123
        type: string
      phone_number:
        example: +855-17-345-6790
        type: string
    type: object
  utils.APIResponse:
    properties:
      message:
        type: string
      status:
        type: string
      success:
        type: boolean
    type: object
  utils.Response:
    properties:
      data: {}
      message:
        example: Login successful
        type: string
      status:
        example: "200"
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for EduVision Scholarship Portal
  title: EduVision for Scholarship Portal API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.LoginResponse'
              type: object
      summary: Login into user account
      tags:
      - Users
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Registration successful
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
